version: '4'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: emilienmottet/nasm
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    security_opt:
      - seccomp:unconfined
    container_name: nasm_debug_in_project
    ports:
      - "22:22"
      - "7777:7777"
    volumes:
      - .:/home/debugger/code
    working_dir: /home/debugger/code
    hostname: debug